# Generated by Django 3.1.7 on 2021-04-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('same', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=6)),
                ('dob', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('number', models.CharField(max_length=11)),
                ('street_address', models.CharField(max_length=100)),
                ('street_address_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('mp', models.CharField(choices=[('Six Months', 'Six Months'), ('One Year', 'One Year'), ('Two Years', 'Two Years')], max_length=10)),
                ('text', models.TextField()),
                ('confirm', models.BooleanField(default=False)),
            ],
        ),
    ]
